#!/usr/bin/env bash
# Digitisation parameters for the 14C(d,p)15C field x pitch study: D2 at 300 torr.
#
#   ./make_dp_pars.sh [magboltz_dir]
#
# Built from parameters/ATTPC.a1954_C14_sim.par -- the (p,p') campaign's par -- so that everything
# not related to the gas is IDENTICAL between the two channels and a difference between them is
# the reaction and not a setting. What changes:
#
#   Density        0.0656 mg/cm3   D2 at 300 torr -- matched EXACTLY to the transport geometry
#                                  ATTPC_D300torr_v2 (6.5643e-5 g/cm3). a1975's D2 par carries
#                                  0.0661 against the same geometry, a 0.7 % mismatch between what
#                                  is transported and what is digitised. Small, but it is the same
#                                  class of defect that cost a1954 7.4 %, so it is not inherited.
#   DriftVelocity  1.10424 cm/us   measured on a1975 D2 data at the same 5000 V/m
#   Gain           150000          the (p,p') campaign's value, NOT a1975's measured D2 35000.
#                                  MEASURED REASON, 2026-08-29: at 35000 the 2 mm arm is starved.
#                                  A 2 x 2 mm pad collects 1/24 of the charge of an 8 x 12 mm one,
#                                  so at a fixed PSA threshold the fine plane loses hits: the first
#                                  (d,p) run at 35000 gave 1870 usable protons with AT-TPC pads and
#                                  848 with 2 mm, while the (p,p') campaign at 150000 gave 3222 and
#                                  3297 -- identical. Running the pitch comparison at a gain the
#                                  fine plane cannot work at measures the threshold, not the pitch.
#                                  This is a real design constraint in its own right: a 2 mm plane
#                                  needs roughly 4x the gain, or a proportionally lower threshold.
#   BField, CoefT  per field, below
#
# DIFFUSION. Same treatment as the (p,p') campaign, and for the same reason: the digitiser turns
# CoefT into sigma_T = 10*sqrt(2*CoefT*t), which at full drift with the legacy 9e-4 is larger than
# a 2 mm pad, so holding it fixed across fields would hide the one thing a strong field does to a
# TPC besides bending tracks. The field dependence comes from Magboltz for D2 at 300 torr, 50 V/cm,
# B parallel to E; the 2.85 T value is HELD at the legacy 9e-4 that both the a1954 and a1975 par
# files use, and only the ratio is taken. That keeps the two channels on the same footing.
set -eo pipefail
MB=${1:-/home/yassid/attpc_diff_H2}
REPO=/home/yassid/fair_install/ATTPCROOTv2-OpenKF
SRC="$REPO/parameters/ATTPC.a1954_C14_sim.par"
for b in 0.0 2.85 4.0 7.0; do
   [ -s "$MB/d2_B$b.txt" ] || { echo "missing $MB/d2_B$b.txt -- run run_d2diff.sh first"; exit 1; }
done
get() { awk -v c="$2" '!/^#/{print $c; exit}' "$MB/d2_B$1.txt"; }
DT0=$(get 0.0 7); DT285=$(get 2.85 7); DT400=$(get 4.0 7); DT700=$(get 7.0 7)
DL0=$(get 0.0 6); DL285=$(get 2.85 6); DL400=$(get 4.0 6); DL700=$(get 7.0 6)
VD285=$(get 2.85 4)
echo "Magboltz, D2 300 torr 293 K, E = 50 V/cm, B || E:"
printf "  %-5s %10s %16s %16s\n" "B[T]" "vd[cm/us]" "DL[um/sqrt(cm)]" "DT[um/sqrt(cm)]"
for b in 0.0 2.85 4.0 7.0; do printf "  %-5s %10s %16s %16s\n" "$b" "$(get $b 4)" "$(get $b 6)" "$(get $b 7)"; done
LEGACY=0.0009
CT400=$(awk -v a="$DT400" -v r="$DT285" -v l="$LEGACY" 'BEGIN{printf "%.6f", l*(a/r)^2}')
CT700=$(awk -v a="$DT700" -v r="$DT285" -v l="$LEGACY" 'BEGIN{printf "%.6f", l*(a/r)^2}')
echo "anchored CoefT: 2.85 T $LEGACY   4.0 T $CT400   7.0 T $CT700  (cm2/us)"

write_par() { # tag B CoefT
   local out="$REPO/parameters/ATTPC.a1954_C14dp_$1.par"
   {
      echo "##############################################################################"
      echo "# 14C(d,p)15C FIELD x PAD-PITCH STUDY -- D2 at 300 torr, B = $2 T"
      echo "#"
      echo "# Generated by macro/Simulation/ATTPC/14C_dp/make_dp_pars.sh on $(date +%F)."
      echo "# Base: parameters/ATTPC.a1954_C14_sim.par, so everything not gas-related is identical"
      echo "# to the (p,p') campaign and the two channels differ by the reaction alone."
      echo "#"
      echo "# Gas: D2 at 300 torr, 293 K. Density 0.065643 mg/cm3, set EQUAL to the transport"
      echo "# geometry ATTPC_D300torr_v2 rather than to a1975's 0.0661, so digitisation and"
      echo "# transport model the same gas. TWICE the mass density of the a1954 H2 but the SAME"
      echo "# electron density, so the beam loses the same ~10 MeV over the metre."
      echo "# DriftVelocity 1.10424 cm/us, measured on a1975 D2 data at this field."
      echo "# Gain 150000, as the (p,p') campaign. a1975's measured D2 gain of 35000 starves a 2 mm"
      echo "# pad plane at the standard threshold -- see the header of make_dp_pars.sh."
      echo "#"
      echo "# Transverse diffusion from Magboltz (D2, 300 torr, 293 K, 50 V/cm, B || E), anchored"
      echo "# on the legacy 9e-4 at 2.85 T and scaled by (DT(B)/DT(2.85))^2:"
      echo "#     DT = $DT0 / $DT285 / $DT400 / $DT700 um/sqrt(cm) at 0 / 2.85 / 4 / 7 T"
      echo "#     DL = $DL0 / $DL285 / $DL400 / $DL700 (field-independent, as it must be for B || E)"
      echo "#     Magboltz drift velocity at 2.85 T: $VD285 cm/us against the adopted 1.10424"
      echo "##############################################################################"
      grep -v '^#' "$SRC" | awk -v b="$2" -v ct="$3" '
         /^BField:/         {printf "BField:Double_t %14s   # Tesla\n", b; next}
         /^CoefT:/          {printf "CoefT:Double_t  %14s   # Transverse diffusion [cm^2/us], see header\n", ct; next}
         /^Density:/        {printf "Density:Double_t %13s   # mg/cm3. D2 300 torr, = the transport geometry\n", "0.065643"; next}
         /^DriftVelocity:/  {printf "DriftVelocity:Double_t %7s # cm/us. D2, measured on a1975 data\n", "1.10424"; next}
         /^Gain:/           {printf "Gain:Double_t   %14s   # as the pp campaign; 35000 starves 2 mm pads\n", "150000"; next}
         {print}'
   } > "$out"
   echo "wrote $out"
}
write_par b285 2.85 "$LEGACY"
write_par b400 4.0  "$CT400"
write_par b700 7.0  "$CT700"
echo
echo "check: values that must have changed from the (p,p') par"
for t in b285 b400 b700; do
  printf "  %-5s " "$t"
  grep -hE "^(Density|DriftVelocity|Gain|BField|CoefT):" "$REPO/parameters/ATTPC.a1954_C14dp_$t.par" | awk '{printf "%s=%s ", $1, $2}'
  echo
done
