/// @file exc_vs_fresco_C14.C
/// @brief Overlay the extracted excited-state angular distributions on single-multipole DWBA.
///
/// This is a test of the level assignment, not a fit to it: the components were separated using
/// only their ENERGIES, so their angular SHAPES are an independent prediction of the assigned
/// spin-parities. A 3- should not look like a 2+.
///
/// Multipole assignment for the calculations:
///     6.09  (1-)  ->  L = 1
///     6.70  (3-)  ->  L = 3
///     7.00  (2+)  ->  L = 2
///     7.27  (2-)  ->  NO CALCULATION. 0+ -> 2- is an unnatural-parity transition and cannot be
///                     generated by the collective (type=11) deformation used here, which only
///                     produces natural-parity states. Its panel shows the data alone.
///
/// The calculations were run at E_lab(p) = 11.581 MeV, corresponding to a 161 MeV beam; the
/// excited-state calibration prefers 164.25 MeV, i.e. E_lab(p) = 11.82 MeV. The predicted SHAPE
/// is insensitive to that difference (comparing the 155 and 161 MeV curves for the elastic
/// channel changes it by well under the data errors), so the existing curves are used.
///
/// Each curve carries one free normalisation, fitted over the angular range where the data have
/// their best statistics. The comparison is of shape only -- the deformation length used in the
/// calculation is a reference value, not a fitted one.
///
///   root -b -q 'exc_vs_fresco_C14.C()'

void exc_vs_fresco_C14(TString dataFile = "plots/exc_angdist_gfex.root", TString frDir = "",
                       TString accDir = "/mnt/f/a1954_C14_acc_gf_nochi2/", Double_t normLo = 40.0,
                       Double_t normHi = 110.0, Bool_t doFold = kTRUE, TString outTag = "")
{
   gStyle->SetOptStat(0);
   TString here = gSystem->DirName(gInterpreter->GetCurrentMacroName());
   if (frDir.IsNull())
      frDir = here + "/../fresco/outputs/";

   const int NLV = 4;
   const char *LVNAME[NLV] = {"6.09 (1^{-})", "6.70 (3^{-})", "7.00 (2^{+})", "7.27 (2^{-})"};
   const char *FRF[NLV] = {"p14C_inel_161_6094_L1_dsdo_ex2.dat", "p14C_inel_161_6728_L3_dsdo_ex2.dat",
                           "p14C_inel_161_7012_L2_dsdo_ex2.dat", ""};
   const char *LTXT[NLV] = {"DWBA L = 1", "DWBA L = 3", "DWBA L = 2", "(unnatural parity: no DWBA)"};
   const int LVCOL[NLV] = {kAzure + 2, kRed + 1, kGreen + 3, kOrange + 7};

   TFile *fd = TFile::Open(here + "/" + dataFile);
   if (!fd || fd->IsZombie()) {
      printf("\033[1;31mmissing %s -- run exc_angdist_C14.C first\033[0m\n", dataFile.Data());
      return;
   }
   TH1D *dat[NLV];
   for (int i = 0; i < NLV; ++i) {
      auto *h = (TH1D *)fd->Get(TString::Format("dsdo_%d", i));
      if (!h) {
         printf("\033[1;31mno dsdo_%d in %s\033[0m\n", i, dataFile.Data());
         return;
      }
      dat[i] = (TH1D *)h->Clone(TString::Format("d%d", i));
      dat[i]->SetDirectory(nullptr);
   }
   fd->Close();

   // response and acceptance, for the fold (same construction as the elastic analysis)
   std::map<double, double> acc;
   std::vector<std::array<double, 3>> R;
   if (doFold) {
      TFile *fa = TFile::Open(accDir + "acceptance_merged_ex1.root");
      auto *a = fa && !fa->IsZombie() ? (TH1D *)fa->Get("hAcc_ex1_sum") : nullptr;
      if (a)
         for (int b = 1; b <= a->GetNbinsX(); ++b)
            acc[a->GetBinCenter(b)] = a->GetBinContent(b);
      if (fa) fa->Close();
      std::ifstream in((here + "/plots/ompfit/response.txt").Data());
      std::string l;
      while (std::getline(in, l)) {
         if (l.empty() || l[0] == '#')
            continue;
         std::istringstream is(l);
         double t, r, p;
         if (is >> t >> r >> p)
            R.push_back({t, r, p});
      }
      if (acc.empty() || R.empty()) {
         printf("\033[1;33mno acceptance or response -- comparing to the RAW calculation\033[0m\n");
         doFold = kFALSE;
      }
   }

   auto loadFR = [&](const char *fn) -> TGraph * {
      if (!fn || !*fn)
         return nullptr;
      auto *g = new TGraph();
      std::ifstream in((frDir + fn).Data());
      double a, x;
      int n = 0;
      while (in >> a >> x)
         g->SetPoint(n++, a, x);
      if (g->GetN() == 0) {
         printf("\033[1;31mcannot read %s\033[0m\n", fn);
         return nullptr;
      }
      if (!doFold)
         return g;
      std::map<double, double> num;
      for (auto &e : R) {
         double at = acc.count(e[0]) ? acc[e[0]] : 0;
         if (at <= 0)
            continue;
         num[e[1]] += e[2] * at * g->Eval(e[0]) * std::sin(e[0] * TMath::DegToRad());
      }
      auto *o = new TGraph();
      int m = 0;
      for (auto &kv : num) {
         double ar = acc.count(kv.first) ? acc[kv.first] : 0, s = std::sin(kv.first * TMath::DegToRad());
         if (ar > 0.05 && s > 1e-3)
            o->SetPoint(m++, kv.first, kv.second / ar / s);
      }
      return o;
   };

   TCanvas *c = new TCanvas("c", "excited states vs DWBA", 1400, 950);
   c->Divide(2, 2);
   printf("\n===== excited-state shapes against single-multipole DWBA (%s) =====\n",
          doFold ? "resolution folded" : "RAW");
   for (int i = 0; i < NLV; ++i) {
      c->cd(i + 1);
      gPad->SetLogy();
      TGraph *fr = loadFR(FRF[i]);
      double k = 1;
      if (fr) {
         double sn = 0, sd = 0;
         for (int b = 1; b <= dat[i]->GetNbinsX(); ++b) {
            double x = dat[i]->GetBinCenter(b), y = dat[i]->GetBinContent(b), e = dat[i]->GetBinError(b);
            if (x < normLo || x > normHi || y <= 0 || e <= 0)
               continue;
            double f = fr->Eval(x);
            if (f <= 0)
               continue;
            sn += y * f / (e * e);
            sd += f * f / (e * e);
         }
         k = sn > 0 ? sn / sd : 1; // scale the CURVE onto the data
      }
      double mx = dat[i]->GetMaximum();
      auto *frm = new TH1D(TString::Format("f%d", i),
                           TString::Format("%s%s;#theta_{cm} [deg];d#sigma/d#Omega [arb]", LVNAME[i],
                                           doFold ? "" : "   (RAW DWBA)"),
                           1, 15, 145);
      frm->SetMinimum(std::max(1.0, mx * 3e-3));
      frm->SetMaximum(mx * 6);
      frm->Draw();
      if (fr) {
         auto *g2 = new TGraph(*fr);
         for (int n = 0; n < g2->GetN(); ++n)
            g2->SetPointY(n, g2->GetPointY(n) * k);
         g2->SetLineColor(kBlack);
         g2->SetLineWidth(3);
         g2->Draw("L same");
      }
      dat[i]->SetMarkerStyle(20);
      dat[i]->SetMarkerColor(LVCOL[i]);
      dat[i]->SetLineColor(LVCOL[i]);
      dat[i]->SetLineWidth(2);
      dat[i]->SetMarkerSize(1.2);
      dat[i]->Draw("E1 same");
      auto *lg = new TLegend(0.45, 0.74, 0.89, 0.88);
      lg->AddEntry(dat[i], "data", "lp");
      lg->AddEntry((TObject *)nullptr, LTXT[i], "");
      lg->SetTextSize(0.038);
      lg->Draw();

      // how well does the shape agree?
      if (fr) {
         std::vector<double> lr;
         printf("\n  %-14s  theta_cm : data / DWBA\n", LVNAME[i]);
         for (int b = 1; b <= dat[i]->GetNbinsX(); ++b) {
            double x = dat[i]->GetBinCenter(b), y = dat[i]->GetBinContent(b), e = dat[i]->GetBinError(b);
            double f = fr->Eval(x) * k;
            if (f <= 0)
               continue;
            // A bin consistent with zero carries no shape information and drives ln(y/f) to -inf.
            // Report it, but keep it out of the summary -- letting it in has twice produced an
            // rms of 6.3 that described one empty bin rather than the agreement.
            if (y <= 0 || y < 2 * e) {
               printf("      %5.0f : %6.2f   (consistent with zero -- excluded from the rms)\n", x,
                      y > 0 ? y / f : 0.0);
               continue;
            }
            printf("      %5.0f : %6.2f\n", x, y / f);
            lr.push_back(std::log(y / f));
         }
         double c2 = 0;
         for (double v : lr)
            c2 += v * v;
         std::sort(lr.begin(), lr.end());
         double med = lr.empty() ? 0 : std::exp(lr[lr.size() / 2]);
         printf("      rms of ln(data/DWBA) = %.3f over %zu usable bins   (median ratio %.2f)\n",
                lr.empty() ? 0 : std::sqrt(c2 / lr.size()), lr.size(), med);
      }
   }
   TString png = here + "/plots/exc_vs_fresco_C14" + outTag + ".png";
   c->SaveAs(png);
   printf("\nwrote %s\n\n", png.Data());
}
