/// @file ex_kin_dp.C
/// @brief Proton KE vs theta_lab "kinematics" plot for 16C(d,p)17C, with the
///        theoretical two-body kinematic curves (Ex = 0, 5, 10 MeV) overlaid.
///        Reads the cached ntuple proton_kin_dp.root produced by ex_dp_a1975.C.
///
///   root -l -b -q 'ex_kin_dp.C'                 // default Ebeam=192
///   root -l -b -q 'ex_kin_dp.C(192.0)'
///
/// The curves are generated by scanning, at each theta_lab, the proton KE and
/// recording where kine_2b(...)->Ex crosses the target value (handles both lab
/// branches of the inverse-kinematics locus). If the data band sits on the Ex=0
/// (red) curve, the Ex scale is calibrated; the vertical gap between the data ridge
/// and the red curve is the calibration offset.

#include <vector>

static double omega2(double x, double y, double z)
{
   return std::sqrt(x * x + y * y + z * z - 2 * x * y - 2 * y * z - 2 * x * z);
}

// two-body kinematics (same as ex_dp_a1975.C): returns Ex given (thetalab[rad], K_eject)
static double kine_ex(double m1, double m2, double m3, double m4, double K_proj, double thetalab, double K_eject)
{
   double Et1 = K_proj + m1, Et3 = K_eject + m3;
   double s = m1 * m1 + m2 * m2 + 2 * m2 * Et1;
   double u = m2 * m2 + m3 * m3 - 2 * m2 * Et3;
   double arg = (std::cos(thetalab) * omega2(s, m1 * m1, m2 * m2) * omega2(u, m2 * m2, m3 * m3) -
                 (s - m1 * m1 - m2 * m2) * (m2 * m2 + m3 * m3 - u)) /
                   (2 * m2 * m2) +
                s + u - m2 * m2;
   if (arg <= 0)
      return -1e9;
   return std::sqrt(arg) - m4;
}

// build the KE(theta_lab) curve for a fixed Ex by scanning KE and catching Ex crossings
static TGraph *kin_curve(double m1, double m2, double m3, double m4, double Ebeam, double exTarget, double thLoDeg,
                         double thHiDeg, double keMax)
{
   TGraph *g = new TGraph();
   int np = 0;
   for (double thd = thLoDeg; thd <= thHiDeg; thd += 0.5) {
      double th = thd * TMath::DegToRad();
      double prevE = kine_ex(m1, m2, m3, m4, Ebeam, th, 0.02), prevK = 0.02;
      for (double ke = 0.04; ke <= keMax; ke += 0.02) {
         double e = kine_ex(m1, m2, m3, m4, Ebeam, th, ke);
         if (prevE > -1e8 && e > -1e8 && (prevE - exTarget) * (e - exTarget) <= 0) {
            double frac = (exTarget - prevE) / (e - prevE);
            g->SetPoint(np++, thd, prevK + frac * (ke - prevK)); // linear interp KE at crossing
         }
         prevE = e;
         prevK = ke;
      }
   }
   return g;
}

void ex_kin_dp(double Ebeam = 192.0, double keMax = 50.0, const char *cache = "proton_kin_dp.root")
{
   gStyle->SetOptStat(0);
   gStyle->SetPalette(kBird);
   gStyle->SetNumberContours(255);
   const double u = 931.49401;
   const double m_C16 = 16.0147013 * u, m_d = 2.01410178 * u, m_p = 1.00782503 * u, m_C17 = 17.0225864 * u;

   TFile *f = TFile::Open(cache);
   TNtuple *t = (TNtuple *)f->Get("pk");
   if (!t) {
      printf("no ntuple 'pk' in %s — run ex_dp_a1975.C first\n", cache);
      return;
   }

   TH2F *hk =
      new TH2F("hk", "^{16}C(d,p)^{17}C kinematics;#theta_{lab} [deg];proton KE [MeV]", 180, 0, 180, 150, 0, 25);
   t->Draw("ke:theta>>hk", "chi2ndf<5", "goff");

   // theoretical curves for a few Ex
   double exVals[] = {0.0, 5.0, 10.0};
   Color_t cols[] = {kRed, kAzure + 1, kGreen + 2};
   TGraph *gc[3];
   for (int i = 0; i < 3; ++i) {
      gc[i] = kin_curve(m_C16, m_d, m_p, m_C17, Ebeam, exVals[i], 1, 150, keMax);
      gc[i]->SetLineColor(cols[i]);
      gc[i]->SetLineWidth(3);
      gc[i]->SetMarkerColor(cols[i]);
      gc[i]->SetMarkerStyle(1);
   }

   TCanvas *c = new TCanvas("c", "kin_dp", 1100, 800);
   c->SetRightMargin(0.13);
   hk->Draw("colz");
   for (int i = 0; i < 3; ++i)
      gc[i]->Draw("P same");

   TLegend *leg = new TLegend(0.62, 0.70, 0.86, 0.88);
   leg->SetHeader(Form("two-body, E_{beam}=%.0f MeV", Ebeam));
   for (int i = 0; i < 3; ++i)
      leg->AddEntry(gc[i], Form("E_{x} = %.0f MeV", exVals[i]), "p");
   leg->Draw();

   c->SaveAs("plots/kin_dp.png");
   printf("saved plots/kin_dp.png  (red=g.s. Ex=0; data ridge offset from red = Ex calibration gap)\n");
}
