#!/usr/bin/env bash
# a1975 16C(d,t)15C genfit production at dv 1.10424, WITH material effects, using the CATIMA
# backend. Supersedes the genfit arm of fit_dt_dv1104.sh, which runs matEffects = kFALSE.
#
# WHAT CHANGED FROM fit_dt_dv1104.sh, AND WHY EACH ONE
#
#   matEffects kFALSE -> kTRUE.  The point of the exercise. It was off because genfit's own
#       material models leave 62% of triton fits with ndf < 0 -- collapsed fits that still carry
#       kinematics and so are invisible unless ndf is checked. With CATIMA that is 3%.
#
#   catimaMSC = catimaStraggling = kTRUE.  Needs a GenFit built -DGENFIT_USE_CATIMA=ON. Both are
#       required: the collapse is a CONJUNCTION, and removing either one (or the table below)
#       puts it back to ~50%. Straggling is the term that actually drives it; the MSC model on
#       its own moves 62% -> 56%.
#
#   eLossTable = triton_D2_300torr.txt.  Below beta*gamma = 0.05 (KE = 3.5 MeV for a triton)
#       genfit applies NO stopping power without a curve loaded, and the (d,t) low branch is
#       0.8-6 MeV. Regenerated 2026-08-16 with deuterium's real mass 2.014 rather than a round 2,
#       which had been a flat +0.70% on every point.
#
#   manualElossDensity 6.61e-5 -> 0.  THE ONE THAT IS EASY TO GET WRONG. With material effects
#       ON, extrapolateToLine already transports the state back through the gas with genfit's own
#       RK4 dE/dx, so the vertex-gap loss is ALREADY in KE_xtr. SetManualELoss then adds
#       GetEnergyLoss(KE, vtxGapCm) on top of it -- it is documented as being for the
#       material-effects-OFF case, where the extrapolation is geometric and leaves |p| untouched,
#       but nothing in the code enforces that. Passing 0 disables ONLY SetManualELoss:
#       SetELossHybrid falls back to 6.61e-5 internally and the range constraint is separate.
#       Measured cost of leaving it in: +5.25% on the low branch of KE_xtr, which is the slot the
#       Ex analysis reads, and a 14% wider low-branch distribution.
#
#   matFallback kTRUE -> kFALSE.  A throwing track is NOT silently refitted with
#       setNoEffects(true) and kept. This keeps the production a single physics model and
#       directly comparable to the run_0031 arms. The alternative (kTRUE) would preserve a few
#       percent more yield but every consumer would then have to filter on
#       GetMatEffectsFallback(), and not filtering is exactly how a blended spectrum happens.
#
#   catimaELoss kFALSE -> kTRUE (added 2026-08-17). dE/dx below beta*gamma = 0.05 now comes from
#       catima::dedx + dedx_n evaluated with the STEP's own material, instead of the ASCII curve
#       above multiplied by ONE GLOBAL density. MEASURED on 8 runs x 3 arms
#       (`ab_dt_catimaeloss.sh`, spread over the formerly-worst and formerly-best runs):
#
#         arm                   usable   collapsed   3.103 peak
#         table (control)        5808      2.53%     2.942 +- 0.032
#         CATIMA below bg=0.05   5905      0.94%     2.918 +- 0.033
#         CATIMA full range      5905      0.96%     2.919 +- 0.034
#
#       WHAT IT BUYS IS FIT STABILITY, NOT ENERGY SCALE. Collapsed fits 2.53% -> 0.94% (~7 sigma),
#       i.e. free statistics. The 3.103 peak does NOT move toward truth (0.024 +- 0.046, consistent
#       with zero) and the width does not improve. That is the expected result once you notice the
#       ASCII table was GENERATED by CATIMA: native computation reproduces the same physics, it is
#       simply no longer frozen, no longer per-species/gas/pressure, and no longer stuck with a
#       single global density. So this does NOT address the ~0.2-0.3 MeV deficit on 3.103; that
#       suspect is now eliminated and the cause is upstream (drift velocity, beam energy, geometry).
#
#   catimaELossFull left kFALSE. The full-range arm replaces Bethe-Bloch too and changes NOTHING
#       (2.918 -> 2.919, collapse 0.94% -> 0.96%): genfit's Bethe-Bloch already tracks CATIMA to
#       0.2-2% above 1 MeV. Smaller change from a validated baseline for identical benefit.
#
# NOTHING IS OVERWRITTEN. This writes to gf_dt_cateloss/, alongside gf_dt_catima/, which is the
# production behind the current dt_kin_catima.root and stays exactly as it is. The two differ in
# ONE flag, so they can be differenced directly.
#
# UNCHANGED: gate, geometry, par file, beam energy, gas density, iteration counts, theta window,
# measSigma. Same reco input as the dv 1.10424 production.
#
#   ./prod_dt_catima.sh [nparallel] [runs...]
cd /home/yassid/fair_install/ATTPCROOTv2-OpenKF/macro/Unpack_HDF5/a1975/D2_UKF
# config.sh reads unset vars: source it BEFORE set -u or it kills the script silently
source /home/yassid/fair_install/ATTPCROOTv2-OpenKF/build/config.sh >/dev/null 2>&1
export GENFIT=/home/yassid/fair_install/GenFit
export LD_LIBRARY_PATH=$GENFIT/lib:${LD_LIBRARY_PATH:-}
export ROOT_INCLUDE_PATH=/home/yassid/fair_install/ATTPCROOTv2-OpenKF/build/include:${ROOT_INCLUDE_PATH:-}
set -uo pipefail

NPAR="${1:-6}"; shift || true
RUNS="${*:-0016 0017 0018 0019 0020 0021 0022 0023 0026 0027 0031 0032 0034 0036 0037 0038 0039 0040 0041 0042 0043 0044 0046 0048 0057 0058 0076 0077 0078 0079 0080 0082 0083 0084 0085 0086 0087 0088 0089 0091 0092 0095 0096 0097 0098 0102 0103}"

export REC=/mnt/f/a1975/reco_d2_dv1104/
export GF="${GF:-/mnt/f/a1975/gf_dt_cateloss/}"
export LOG="${LOG:-/mnt/f/a1975/logs_dt_cateloss/}"
export PAR=ATTPC.a1975_deuterium_dv1104.par
export GATE=pid/triton_d2_dv1104.json
export TAB=triton_D2_300torr.txt
# dE/dx source. ADOPTED DEFAULT 2026-08-17: native CATIMA below beta*gamma=0.05, Bethe-Bloch
# above it. Env-overridable so the full-range variant needs no edit to this file:
#   CFULL=kTRUE GF=/mnt/f/a1975/gf_dt_catfull/ LOG=/mnt/f/a1975/logs_dt_catfull/ ./prod_dt_catima.sh 4
export CEL="${CEL:-kTRUE}"
export CFULL="${CFULL:-kFALSE}"
mkdir -p "$GF" "$LOG"

one() {
  n="$1"; r="run_${n}"
  rc="${REC}${r}_multifit_reco.root"
  [ -s "$rc" ] || { echo "[noreco] $r"; return 0; }
  fo="${GF}${r}_multifit_genfitter_t.root"
  [ -s "${fo}.done" ] && { echo "[have] $r"; return 0; }
  root -l -b -q "fitGenfitter_a1975_deuterium.C(\"${r}_multifit\",-1,\"$REC\",\"\",\"$GF\",\
-2.85,2,5,\"$GATE\",4.0,10.0,170.0,kTRUE,kTRUE,1000010030,3.01550072,1,\"t\",\"_reco\",\
\"ATTPC_D300torr_v2_geomanager.root\",kTRUE,0,2,\"$PAR\",kFALSE,kFALSE,kFALSE,\"$TAB\",kTRUE,kTRUE,${CEL},${CFULL})" \
    > "${LOG}gf_${r}.log" 2>&1
  if grep -qi 'segmentation violation' "${LOG}gf_${r}.log" || [ ! -s "$fo" ]; then
    echo "[FAIL] $r  (see ${LOG}gf_${r}.log)"; rm -f "$fo"
  else
    # a run whose CATIMA backend silently did not engage is worth catching here, not at analysis
    grep -q "CATIMA material model: MSC ON, straggling ON" "${LOG}gf_${r}.log" \
      || echo "[WARN] $r: CATIMA line missing from the log -- backend may not be active"
    # the flag added 2026-08-17: without this banner the run silently used the ASCII table, which
    # is precisely the old production and would look like a valid arm of the comparison
    grep -q "dE/dx from CATIMA" "${LOG}gf_${r}.log" \
      || echo "[WARN] $r: CATIMA dE/dx banner missing -- fell back to the table"
    touch "${fo}.done"; echo "[ok] $r  $(date '+%H:%M:%S')"
  fi
}
export -f one

echo "=== CATIMA (d,t) production: $(echo $RUNS | wc -w) runs, $NPAR parallel -> $GF ==="
printf '%s\n' $RUNS | xargs -P "$NPAR" -I{} bash -c 'one "$@"' _ {}
echo "=== done: $(ls "$GF"/*_genfitter_t.root 2>/dev/null | wc -l) fit files in $GF ==="
