#!/usr/bin/env bash
# Digitisation parameters for the 10Be(t,p)12Be field x pitch study: T2 at 300 torr.
#
#   ./make_tp_pars.sh [magboltz_dir]
#
# Built from parameters/ATTPC.a1954_C14dp_b285.par -- the (d,p) campaign's par -- so that
# everything not related to the gas is IDENTICAL between the two channels and a difference
# between them is the reaction and not a setting. What changes:
#
#   Density        0.0989854 mg/cm3   T2 at 300 torr, 293.15 K, ideal gas. Set EXACTLY equal to
#                                     the transport geometry ATTPC_T300torr (9.89854e-5 g/cm3), so
#                                     transport and digitisation model the same gas. (The D2 par
#                                     carries a 0.7 % legacy offset against its own geometry;
#                                     that is deliberately not inherited.)
#   EIonize        15.603 eV          UNCHANGED. The W value of a hydrogen isotope is set by the
#                                     electronic structure, which is identical for H2/D2/T2.
#   BField, CoefT  per field, below
#
# HELD AT THE (d,p) VALUES ON PURPOSE:
#   DriftVelocity  1.10424 cm/us      There is NO measured electron drift velocity for T2, and
#                                     Magboltz has no tritium. Two things make holding it right:
#                                     (a) the digitiser and the reconstruction read the SAME par,
#                                     so the time-bucket <-> z map is self-consistent and the
#                                     value does not bias Ex -- it only sets the z scale; and
#                                     (b) holding it keeps exactly one thing different between the
#                                     (d,p) and (t,p) campaigns. For the record, the measured
#                                     H2 -> D2 isotope effect in this same Magboltz scan is
#                                     v_d x 0.916 per mass doubling, which extrapolates to about
#                                     -5 % for T2. That is the size of the assumption.
#   Gain           150000             As the (d,p) campaign. Measured reason: at 35000 the 2 mm
#                                     arm is starved -- a 2 x 2 mm pad collects 1/24 of the charge
#                                     of an 8 x 12 mm one, so at a fixed PSA threshold the fine
#                                     plane simply loses hits and the pitch comparison measures
#                                     the threshold instead of the pitch.
#
# DIFFUSION. Same recipe as (d,p) and (p,p'): CoefT is ANCHORED at the legacy 9e-4 at 2.85 T and
# only the RATIO DT(B)/DT(2.85) is taken from Magboltz. That recipe is what makes T2 tractable
# without a T2 gas file: the isotope dependence very largely CANCELS in the ratio. Measured in the
# existing scan, DT(7 T)/DT(2.85 T) is 0.4396 in H2 and 0.4501 in D2 -- a 2.4 % difference over a
# factor-two mass step -- so using the D2 ratios for T2 is good to a few per cent, while the
# absolute DT differs between the isotopes by 18-21 %. Take the ratio, not the value.
set -eo pipefail
MB=${1:-/home/yassid/attpc_diff_H2}
REPO=/home/yassid/fair_install/ATTPCROOTv2-OpenKF
SRC="$REPO/parameters/ATTPC.a1954_C14dp_b285.par"
[ -s "$SRC" ] || { echo "missing $SRC -- run 14C_dp/make_dp_pars.sh first"; exit 1; }
for b in 0.0 2.85 4.0 7.0; do
   [ -s "$MB/d2_B$b.txt" ] || { echo "missing $MB/d2_B$b.txt"; exit 1; }
   [ -s "$MB/h2_B$b.txt" ] || { echo "missing $MB/h2_B$b.txt"; exit 1; }
done
get() { awk -v c="$3" '!/^#/{print $c; exit}' "$MB/$1_B$2.txt"; }
DT285=$(get d2 2.85 7); DT400=$(get d2 4.0 7); DT700=$(get d2 7.0 7); DT0=$(get d2 0.0 7)
DL285=$(get d2 2.85 6)
echo "Magboltz, 300 torr 293 K, E = 50 V/cm, B || E -- ISOTOPE CHECK on the ratio that is used:"
printf "  %-4s %12s %12s %12s %12s\n" "gas" "DT(2.85)" "DT(4)" "DT(7)" "DT7/DT2.85"
for g in h2 d2; do
   a=$(get $g 2.85 7); b=$(get $g 4.0 7); c=$(get $g 7.0 7)
   printf "  %-4s %12s %12s %12s %12s\n" "$g" "$a" "$b" "$c" "$(awk -v x="$c" -v y="$a" 'BEGIN{printf "%.4f", x/y}')"
done
echo "  -> the RATIO moves 2.4 % between H2 and D2 while the VALUE moves 18 %; the ratio is what is used."
LEGACY=0.0009
CT400=$(awk -v a="$DT400" -v r="$DT285" -v l="$LEGACY" 'BEGIN{printf "%.6f", l*(a/r)^2}')
CT700=$(awk -v a="$DT700" -v r="$DT285" -v l="$LEGACY" 'BEGIN{printf "%.6f", l*(a/r)^2}')
echo "anchored CoefT: 2.85 T $LEGACY   4.0 T $CT400   7.0 T $CT700  (cm2/us)"

write_par() { # tag B CoefT
   local out="$REPO/parameters/ATTPC.Be10tp_$1.par"
   {
      echo "##############################################################################"
      echo "# 10Be(t,p)12Be FIELD x PAD-PITCH STUDY -- T2 at 300 torr, B = $2 T"
      echo "#"
      echo "# Generated by macro/Simulation/ATTPC/10Be_tp/make_tp_pars.sh on $(date +%F)."
      echo "# Base: parameters/ATTPC.a1954_C14dp_b285.par, so everything not gas-related is"
      echo "# identical to the 14C(d,p) campaign and the two channels differ by the reaction"
      echo "# and the target gas alone."
      echo "#"
      echo "# Gas: T2 at 300 torr, 293.15 K. Density 0.0989854 mg/cm3, set EQUAL to the transport"
      echo "# geometry ATTPC_T300torr, so digitisation and transport model the same gas. Same"
      echo "# molecular number density -- hence the same ELECTRON density -- as the H2 and D2"
      echo "# fills of the sibling campaigns."
      echo "# DriftVelocity 1.10424 cm/us is the D2 value, HELD: no T2 measurement exists and"
      echo "# Magboltz has no tritium. It is self-consistent (digi and reco read this same par) so"
      echo "# it sets only the z scale. Isotope extrapolation from the H2->D2 step suggests ~-5 %."
      echo "# Gain 150000, as the (d,p) campaign; 35000 starves a 2 mm pad plane."
      echo "#"
      echo "# Transverse diffusion: anchored on the legacy 9e-4 at 2.85 T and scaled by"
      echo "# (DT(B)/DT(2.85))^2 from the Magboltz D2 scan (300 torr, 293 K, 50 V/cm, B || E)."
      echo "# The RATIO is what is isotope-robust: DT(7)/DT(2.85) = 0.4396 in H2 vs 0.4501 in D2,"
      echo "# a 2.4 % spread over a factor-two mass change, while the absolute DT moves 18-21 %."
      echo "#     DT = $DT0 / $DT285 / $DT400 / $DT700 um/sqrt(cm) at 0 / 2.85 / 4 / 7 T (D2)"
      echo "#     DL = $DL285 um/sqrt(cm), field-independent, as it must be for B || E"
      echo "##############################################################################"
      grep -v '^#' "$SRC" | awk -v b="$2" -v ct="$3" '
         /^BField:/         {printf "BField:Double_t %14s   # Tesla\n", b; next}
         /^CoefT:/          {printf "CoefT:Double_t  %14s   # Transverse diffusion [cm^2/us], see header\n", ct; next}
         /^Density:/        {printf "Density:Double_t %13s  # mg/cm3. T2 300 torr, = the transport geometry\n", "0.0989854"; next}
         /^DriftVelocity:/  {printf "DriftVelocity:Double_t %7s # cm/us. HELD at the D2 value, see header\n", "1.10424"; next}
         {print}'
   } > "$out"
   echo "wrote $out"
}
write_par b285 2.85 "$LEGACY"
write_par b400 4.0  "$CT400"
write_par b700 7.0  "$CT700"
echo
echo "check: values that must differ from the (d,p) par, and those that must NOT"
for t in b285 b400 b700; do
  printf "  %-5s " "$t"
  grep -hE "^(Density|DriftVelocity|Gain|BField|CoefT|EIonize):" "$REPO/parameters/ATTPC.Be10tp_$t.par" | awk '{printf "%s=%s ", $1, $2}'
  echo
done
