#!/usr/bin/env bash
# Write the digitisation parameter files for the 14C(p,p') field x pitch campaign.
#
#   ./make_hf_pars.sh [magboltz_dir]      (default ~/attpc_diff_H2)
#
# Three fields x two diffusion treatments:
#   ATTPC.a1954_C14_hf_b285.par / _b400.par / _b700.par
#       BField set, and CoefT scaled with the field as Magboltz says it scales.
#   ATTPC.a1954_C14_hf_b400_fixdiff.par / _b700_fixdiff.par
#       BField set, CoefT held at the legacy 9e-4 -- the CONTROL that separates "the field bent
#       the tracks better" from "the field stopped the electrons spreading". (b285_fixdiff would
#       be identical to b285 and is not written; the accumulate script maps it to b285.)
#
# WHY CoefT IS NOT JUST COPIED. The digitiser turns it into
#     sigma_T [mm] = 10 * sqrt(2 * CoefT * t_drift[us])
# so at the full 1 m drift (t = 77 us at 1.30 cm/us) the legacy 9e-4 cm^2/us gives sigma_T =
# 3.7 mm -- nearly twice a 2 mm pad. Holding that fixed across the campaign would test 2 mm pads
# in a regime where diffusion, not pitch, sets the transverse resolution, and would hide the one
# thing a high field does to a TPC besides bending tracks: it magnetises the drift electrons and
# suppresses transverse diffusion by 1/(1+(omega*tau)^2). That is the whole reason fine pads and
# high field are proposed together.
#
# THE ANCHOR. The legacy 9e-4 is not replaced by the absolute Magboltz number: it was tuned so
# that the a1954 SIMULATION reproduces the measured cluster widths at 2.85 T, and that agreement
# is worth more than an ab-initio coefficient. So the 2.85 T value is kept and only the RATIO is
# taken from Magboltz:
#     CoefT(B) = 9e-4 * [DT_magboltz(B) / DT_magboltz(2.85 T)]^2
# (CoefT scales as D^2 * v_d / 2, and with B parallel to E the drift velocity does not move.)
# The absolute Magboltz values are printed for comparison; if they disagree with 9e-4 by a large
# factor that is worth knowing, but it does not change the anchor.
#
# CoefL IS LEFT ALONE ON PURPOSE. A magnetic field parallel to E does nothing to longitudinal
# diffusion. The scan includes B = 0 so this can be checked rather than asserted.
set -eo pipefail
MB=${1:-/home/yassid/attpc_diff_H2}
REPO=/home/yassid/fair_install/ATTPCROOTv2-OpenKF
SRC="$REPO/parameters/ATTPC.a1954_C14_sim.par"
[ -f "$SRC" ] || { echo "missing $SRC"; exit 1; }

get() { # field B -> column $2 of the magboltz one-liner
   awk -v c="$2" '!/^#/{print $c; exit}' "$MB/h2_B$1.txt"
}
for b in 0.0 2.85 4.0 7.0; do
   [ -s "$MB/h2_B$b.txt" ] || { echo "missing $MB/h2_B$b.txt -- run run_h2diff.sh first"; exit 1; }
done

# columns: 1 B, 2 E, 3 E/N, 4 vd, 5 vderr, 6 DL, 7 DT, 8 CoefL, 9 CoefT, 10 dlerr, 11 dterr
DT0=$(get 0.0 7);  DT285=$(get 2.85 7); DT400=$(get 4.0 7); DT700=$(get 7.0 7)
DL0=$(get 0.0 6);  DL285=$(get 2.85 6); DL400=$(get 4.0 6); DL700=$(get 7.0 6)
VD285=$(get 2.85 4)
CT285=$(get 2.85 9)

echo "Magboltz, H2 300 torr 293 K, E = 50 V/cm, B || E:"
printf "  B[T]  vd[cm/us]  DL[um/sqrt(cm)]  DT[um/sqrt(cm)]  CoefT[cm2/us]\n"
for b in 0.0 2.85 4.0 7.0; do
   printf "  %-5s %9s %16s %16s %16s\n" "$b" "$(get $b 4)" "$(get $b 6)" "$(get $b 7)" "$(get $b 9)"
done
echo "  (legacy par: vd 1.30 cm/us, CoefL = CoefT = 9e-4 cm2/us)"

LEGACY=0.0009
CT400=$(awk -v a="$DT400" -v r="$DT285" -v l="$LEGACY" 'BEGIN{printf "%.6f", l*(a/r)^2}')
CT700=$(awk -v a="$DT700" -v r="$DT285" -v l="$LEGACY" 'BEGIN{printf "%.6f", l*(a/r)^2}')
echo "anchored CoefT: 2.85 T $LEGACY   4.0 T $CT400   7.0 T $CT700  (cm2/us)"

write_par() { # $1 tag, $2 B[T], $3 CoefT, $4 note
   local out="$REPO/parameters/ATTPC.a1954_C14_hf_$1.par"
   {
      echo "##############################################################################"
      echo "# 14C(p,p') FIELD x PAD-PITCH CAMPAIGN -- B = $2 T"
      echo "#"
      echo "# Generated by macro/Simulation/ATTPC/14C_pp/highfield/make_hf_pars.sh on $(date +%F)."
      echo "# Base: parameters/ATTPC.a1954_C14_sim.par (the adopted a1954 simulation par)."
      echo "# Changed: BField -> $2 T, CoefT -> $3 cm2/us. $4"
      echo "#"
      echo "# Transverse diffusion from Magboltz (H2, 300 torr, 293 K, 50 V/cm, B parallel to E),"
      echo "# anchored on the a1954-tuned 9e-4 at 2.85 T and scaled by (DT(B)/DT(2.85))^2:"
      echo "#     B = 0     DT = $DT0 um/sqrt(cm)"
      echo "#     B = 2.85  DT = $DT285"
      echo "#     B = 4.0   DT = $DT400"
      echo "#     B = 7.0   DT = $DT700"
      echo "# Longitudinal diffusion is NOT touched: B parallel to E does not affect it"
      echo "#     (DL = $DL0 / $DL285 / $DL400 / $DL700 um/sqrt(cm) at 0 / 2.85 / 4 / 7 T)."
      echo "#"
      echo "# TWO THINGS TO KNOW ABOUT THE SCAN. First, DriftVelocity is LEFT AT THE ADOPTED 1.30"
      echo "# cm/us: Magboltz gives $VD285 cm/us for pure H2 at 50 V/cm, three times less, and the"
      echo "# 1.30 is a data-derived a1954 number that this study has no business overriding. The"
      echo "# disagreement means the real gas is not the modelled one (mobility three times higher),"
      echo "# so omega*tau is under- rather than over-estimated here. Second, that barely matters"
      echo "# for the RATIO used above: once omega*tau >> 1, DT(B) goes as 1/B and the ratio tends"
      echo "# to 2.85/B regardless of the mobility. At 7 T the two limits give CoefT 1.74e-4 (this"
      echo "# scan) against 1.49e-4 (the 1/B limit) -- 7 % on sigma, which changes nothing."
      echo "#"
      echo "# PadSizeX/Z, PadRows and PadLayers below are INERT -- AtDigiPar has no getters for"
      echo "# them and the pad geometry comes entirely from the AtMap handed to AtPulseTask."
      echo "# Pass padSize_mm to run_reco_C14.C instead."
      echo "##############################################################################"
      grep -v '^#' "$SRC" | awk -v b="$2" -v ct="$3" '
         /^BField:/     {printf "BField:Double_t %14s   # Tesla\n", b; next}
         /^CoefT:/      {printf "CoefT:Double_t  %14s   # Transverse diffusion [cm^2/us], see header\n", ct; next}
         {print}'
   } > "$out"
   echo "wrote $out"
}

write_par b285 2.85 "$LEGACY" "The a1954 anchor: this par is the adopted simulation par with nothing but a header added."
write_par b400 4.0  "$CT400"  ""
write_par b700 7.0  "$CT700"  ""
write_par b400_fixdiff 4.0 "$LEGACY" "CONTROL: diffusion deliberately frozen at the 2.85 T value."
write_par b700_fixdiff 7.0 "$LEGACY" "CONTROL: diffusion deliberately frozen at the 2.85 T value."

# SANITY: the anchor must carry the same VALUES as the adopted sim par. Comparing raw text
# would flag the reformatted columns and the rewritten inline comments, which are not the thing
# being checked -- so compare key/value pairs with the comments stripped.
norm() { grep -v '^#' "$1" | sed 's/#.*//' | awk 'NF{gsub(/[ \t]+/," "); print}' | sort; }
if diff <(norm "$SRC") <(norm "$REPO/parameters/ATTPC.a1954_C14_hf_b285.par") > /dev/null; then
   echo "CHECK OK: b285 carries exactly the values of the adopted sim par"
else
   echo "CHECK FAILED: b285 differs from the adopted sim par in VALUE, not just formatting:"
   diff <(norm "$SRC") <(norm "$REPO/parameters/ATTPC.a1954_C14_hf_b285.par") || true
fi
