#!/usr/bin/env bash
# Digitisation parameters for the 17C(d,p)18C proposal simulation: D2 at 300 torr, B = 2.85 T.
#
#   ./make_c17dp_par.sh
#
# Derived from parameters/ATTPC.a1954_C14dp_b285.par -- the 14C(d,p) reference campaign's 2.85 T
# par -- with NOTHING changed. The gas (D2, 300 torr, 293 K), the field, the drift length, the
# readout and the gain are all identical; only the beam and the reaction differ between the two
# channels, and those live in the sim macro, not here. Keeping the par byte-identical in content is
# the point: it means any difference between the 14C and 17C results is the reaction.
#
# This script exists rather than a bare `cp` so the provenance is written into the file and a
# re-run is reproducible. It VERIFIES the inherited values instead of asserting them, because a
# silently-changed source par would otherwise propagate here unnoticed.
#
# The values it must produce, and why each is what it is:
#
#   Density        0.065643 mg/cm3   D2 at 300 torr, 293 K. Set EQUAL to the transport geometry
#                                    ATTPC_D300torr_v2 (6.5643e-5 g/cm3) so that what is
#                                    transported and what is digitised are the same gas. a1975's
#                                    D2 par carries 0.0661 against the same geometry, a 0.7 %
#                                    mismatch; it is not inherited.
#   DriftVelocity  1.10424 cm/us     measured on a1975 D2 data at this field and 5000 V/m
#   Gain           150000            the a1954 campaign value
#   BField         2.85 T            nominal SOLARIS + AT-TPC
#   CoefT          9e-4 cm2/us       the legacy value both the a1954 and a1975 pars use, which the
#                                    Magboltz D2 scan (300 torr, 293 K, 50 V/cm, B || E) is
#                                    anchored on at 2.85 T. Only the 4 and 7 T entries of that scan
#                                    ever needed scaling, and this campaign is 2.85 T only.
set -eo pipefail
REPO=/home/yassid/fair_install/ATTPCROOTv2-OpenKF
SRC="$REPO/parameters/ATTPC.a1954_C14dp_b285.par"
OUT="$REPO/parameters/ATTPC.C17dp_D300torr_b285.par"

[ -s "$SRC" ] || { echo "missing source par $SRC -- run 14C_dp/make_dp_pars.sh first"; exit 2; }

# VERIFY the inherited gas/field/readout rather than trusting it. Checking the INPUT is the point:
# if the 14C par is ever regenerated with a different gas, this must fail loudly and not quietly
# produce a 17C par describing the wrong detector.
expect() { # key value
   local got
   got=$(awk -v k="^$1:" '$0 ~ k {print $2; exit}' "$SRC")
   awk -v a="$got" -v b="$2" 'BEGIN{d=a-b; if(d<0)d=-d; exit !(d < 1e-9 || (b!=0 && d/b < 1e-6))}' \
      || { echo "SOURCE PAR CHANGED: $1 is '$got', expected '$2' -- inspect $SRC before trusting this"; exit 1; }
   printf "  ok  %-16s %s\n" "$1" "$got"
}
echo "verifying inherited values in $(basename "$SRC"):"
expect Density       0.065643
expect DriftVelocity 1.10424
expect Gain          150000
expect BField        2.85
expect CoefT         0.0009
expect DriftLength   1000
expect NumTbs        512
expect EField        5000

{
   echo "##############################################################################"
   echo "# 17C(d,p)18C -- SOLARIS + AT-TPC proposal simulation (C17p_FRIB_Proposal)"
   echo "# D2 at 300 torr / 293 K, B = 2.85 T, drift 1000 mm, real AT-TPC pad plane."
   echo "#"
   echo "# Generated by macro/Simulation/ATTPC/17C_dp/make_c17dp_par.sh on $(date +%F)."
   echo "# Source: parameters/ATTPC.a1954_C14dp_b285.par, UNCHANGED. The 14C(d,p) reference"
   echo "# campaign and this one differ by the beam and the reaction only -- both of which are set"
   echo "# in the sim macro, not here -- so any difference in the result is the reaction."
   echo "#"
   echo "# Beam for this channel (in C17_dp_sim.C, not in this file): 17C at 8.37 MeV/u ="
   echo "# 142.29 MeV, ReA6, 940 pps. Q(d,p) = +1.959 MeV. 18C has four bound states:"
   echo "# 0 (0+), 1.588 (2+), 2.515 ((2+)), 3.972 ((2,3)+), with S_n = 4.184 MeV."
   echo "#"
   echo "# Gas: Density 0.065643 mg/cm3 is set EQUAL to the transport geometry ATTPC_D300torr_v2"
   echo "# (6.5643e-5 g/cm3), so digitisation and transport model the same gas."
   echo "# DriftVelocity 1.10424 cm/us, measured on a1975 D2 data at this field."
   echo "# CoefT 9e-4 cm2/us is the legacy value the Magboltz D2 scan is anchored on at 2.85 T."
   echo "##############################################################################"
   grep -v '^#' "$SRC"
} > "$OUT"
echo "wrote $OUT"

echo "check: the values this par must carry"
grep -hE "^(Density|DriftVelocity|Gain|BField|CoefT|CoefL|EField|DriftLength|NumTbs|SamplingRate|GasPressure):" "$OUT" \
   | awk '{printf "  %-24s %s\n", $1, $2}'
